//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2_with_a_class_library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmetns
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
